// Automatically generated by astro-icon
// 74a8481a66d36e1bc2cb709b67ad844b94c5a0f379d6630a18a5d391e4835d11

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "bootstrap/291711_blog_feed_news_subscribe_logo_icon"
		| "bootstrap/291716_github_logo_social network_social_icon"
		| "bootstrap/arrow-left-circle"
		| "bootstrap/arrow-right-circle"
		| "bootstrap/astro-logo-light-gradient"
		| "bootstrap/code-branch-svgrepo-com"
		| "bootstrap/coffee-left-2-svgrepo-com"
		| "bootstrap/coffee-left-3-svgrepo-com"
		| "bootstrap/cup-hot-fill"
		| "bootstrap/emoji-frown-fill"
		| "bootstrap/emoji-sunglasses-fill"
		| "bootstrap/github"
		| "bootstrap/heart"
		| "bootstrap/heart-fill"
		| "bootstrap/instagram"
		| "bootstrap/rocket-takeoff"
		| "bootstrap/rss"
		| "bootstrap/sun"
		| "phosphor/arrow-square-out"
		| "phosphor/caret-double-left"
		| "phosphor/coffee"
		| "phosphor/copyright"
		| "phosphor/github"
		| "phosphor/heart"
		| "phosphor/instagram"
		| "phosphor/rocket-launch-duotone"
		| "phosphor/rocket-takeoff"
		| "phosphor/rss"
		| "phosphor/sparkle"
		| "phosphor/tag";
}